(in-package :uclp)

(defmacro push-item! (item-place &optional tag)
  `(progn
     ,@(list-if tag `(tpush! tags ,tag ,item-place))
     (if accum?
	 (if (stringp ,item-place)
	     (apush! accum ,item-place 0 (length ,item-place))
	     (format accum "~a" ,item-place))
	 (qpush! caps ,item-place))))

(defmacro defcap (names spec compile-body &optional closure-body)
  `(defpattern ,names ,`((pat :pat) ,@spec &optional (tag :tag))
	       ,compile-body
     ,@`(,closure-body)))

(defcap (capture <- quote) ()
  `(with-save (curr)
     (when ,(compile-expr opts pat)
       (if accum?
	   (apush! accum str curr-bak curr)
	   (qpush! caps (subseq str curr-bak curr)))
       ,(when tag `(tpush! tags ,tag (subseq str curr-bak curr)))
       t))
  (let ((p (assemble-expr opts pat)))
    (lift-when push-tag! (tag (tpush! tags tag (subseq str curr-bak curr)))
      (pat-lambda (curr accum accum? str caps tags)
	(with-save (curr)
	  (when (funcall p state)
	    (if accum?
		(apush! accum str curr-bak curr)
		(qpush! caps (subseq str curr-bak curr)))
	    (push-tag!)
	    t))))))

(defpattern (drop) ((pat :pat))
  (with-gensyms ($matched)
    `(with-save (caps accum tags)
       (let ((,$matched ,(compile-expr opts pat)))
	 (restore caps accum tags)
	 ,$matched)))
  (let ((p (assemble-expr opts pat)))
    (pat-lambda (caps accum tags)
      (with-save (caps accum tags)
	(let ((matched (funcall p state)))
	  (restore caps accum tags)
	  matched)))))

(defcap (accum %) ()
  (with-gensyms ($matched $accumed)
    `(if accum?
	 ,(compile-expr opts pat)
	 (progn
	   (setf accum? t)
	   (with-save (accum)
	     (let ((,$matched ,(compile-expr opts pat)))
	       (when ,$matched
		 (let ((,$accumed (subseq accum ,(to->back 'accum) (length accum))))
		   (unless (emptyp ,$accumed)
		     (qpush! caps ,$accumed)
		     ,(if tag `(tpush! tags ,tag ,$accumed)))))
	       (restore accum)
	       (setf accum? nil)
	       ,$matched)))))
  (let ((p (assemble-expr opts pat)))
    (lift-when push-tag! (tag (qpush! caps (subseq str curr-bak curr)))
      (pat-lambda (str curr accum? accum caps)
	(if accum?
	    (funcall p state)
	    (progn
	      (setf accum? t)
	      (with-save (curr accum)
		(let ((matched (funcall p state)))
		  (when matched
		    (let ((accumed (subseq accum accum-bak (length accum))))
		      (unless (emptyp accumed)
			(qpush! caps accumed)
			(push-tag!))))
		  (restore accum)
		  (setf accum? nil)
		  matched))))))))
		      

(defcap (group) ()
  (with-gensyms ($matched $capped)
    `(with-save (caps accum?)
       (setf accum? nil)
       (let ((,$matched ,(compile-expr opts pat))
	     (,$capped (cdr ,(to->back 'caps))))
	 (restore accum? caps)
	 (when ,$matched
	   (push-item! ,$capped ,tag)
	   t))))
  (let ((p (assemble-expr opts pat)))
    (lift-cond (push!) ((tag (push-item! capped tag))
			(t (push-item! capped)))
      (pat-lambda (str curr caps tags accum? accum)
	(with-save (caps accum?)
	  (setf accum? nil)
	  (let ((matched (funcall p state))
		(capped (cdr caps-bak)))
	    (restore accum? caps)
	    (when matched
	      (push!)
	      t)))))))

(defun assemble-fn-replace (opts pat replacer tag)
  (let ((p (assemble-expr opts pat)))
    (lift-cond (push!) ((tag (push-item! result tag))
			(t (push-item! result)))
      (pat-lambda (caps tags accum accum?)
	(with-save (caps accum?)
	  (setf accum? nil)
	  (let ((matched? (funcall p state))
		(capped (cdr caps-bak)))
	    (restore caps accum?)
	    (when matched?
	      (let ((result (apply replacer capped)))
		(push!)
		t))))))))
(defun assemble-literal-replace (opts pat replacer tag)
  (let ((p (assemble-expr opts pat)))
    (lift-cond (push!) ((tag (push-item! result tag))
			(t (push-item! result)))
      (pat-lambda (caps tags accum accum?)
	(with-save (caps accum?)
	  (setf accum? nil)
	  (let ((matched? (funcall p state)))
	    (restore caps accum?)
	    (when matched?
	      (let ((result replacer))
		(push!)
		t))))))))

(defcap (replace /) ((replacer :any))
  (with-gensyms ($matched? $capped $result)
    `(with-save (caps accum?)
       (setf accum? nil)
       (let ((,$matched? ,(compile-expr opts pat))
	     ,@(list-if (functionp replacer) `(,$capped (cdr ,(to->back 'caps)))))
	 (restore caps accum?)
	 (when ,$matched?
	   (let ((,$result ,(if (functionp replacer)
				`(apply ,replacer ,$capped)
				`',replacer)))
	     (push-item! ,$result ,tag)
	     t)))))
  (let ((p (assemble-expr opts pat)))
    (lift-cond (push!) ((tag (push-item! result tag))
			(t (push-item! result)))
      (pat-lambda (caps tags accum accum?)
	(with-save (caps accum?)
	  (setf accum? nil)
	  (let ((matched? (funcall p state))
		(capped (cdr caps-bak)))
	    (restore caps accum?)
	    (when matched?
	      (let ((result (if (functionp replacer) (apply replacer capped) replacer)))
		(push!)
		t))))))))

(defcap (cmt) ((replacer :any))
  (with-gensyms ($matched $capped $result)
    `(with-save (caps accum?)
       (setf accum? nil)
       (let ((,$matched ,(compile-expr opts pat))
	     ,@(list-if (functionp replacer) `(,$capped (cdr caps-bak))))
	 (restore caps accum?)
	 (when ,$matched
	   (let ((,$result ,(if (functionp replacer)
				`(apply ,replacer ,$capped)
				`',replacer)))
	     (when ,$result
	       (push-item! ,$result ,tag)
	       t))))))
  (let ((p (assemble-expr opts pat)))
    (lift-cond (push!) ((tag (push-item! result tag))
			(t (push-item! result)))
      (pat-lambda (caps accum accum? tags)
	(with-save (caps accum?)
	  (setf accum? nil)
	  (let ((matched (funcall p state))
		(capped (cdr caps-bak)))
	    (restore caps accum?)
	    (when matched
	      (let ((result (if (functionp replacer) (apply replacer capped) replacer)))
		(when result
		  (push!)
		  t)))))))))

(defpattern (backref ->) ((tag :tag) &optional (other-tag :tag))
  (with-gensyms ($bind $val)
    `(let ((,$bind (backref tags ,tag)))
       (when ,$bind
	 (let ((,$val (tbind-value ,$bind)))
	   (push-item! ,$val ,other-tag))
	 t)))
  (lift-cond (push!) ((other-tag (push-item! val other-tag))
		      (t (push-item! val)))
    (pat-lambda (tags caps accum accum?)
      (when-let ((bind (backref tags tag)))
	(let ((val (tbind-value bind)))
	  (push!))
	t))))

(defpattern (backmatch) ((tag :tag))
  (with-gensyms ($bind $val $strc $valc)
    `(let ((,$bind (backref tags ,tag)))
       (when ,$bind
	 (let ((,$val (tbind-value ,$bind)))
	   (when (and (stringp ,$val)
		      (<= (+ (length ,$val) curr) strlen))
	     (loop for ,$valc of-type character across ,$val
		   for ,$strc of-type character = (char str curr)
		   do (if (char/= ,$valc ,$strc) (return nil))
		      (incf curr)
		   finally (return t)))))))
  (pat-lambda (tags curr strlen str)
    (when-let ((bind (backref tags tag)))
      (let ((val (tbind-value bind)))
	(when (and (stringp val)
		   (<= (+ (length val) curr) strlen))
	  (loop for valc of-type character across val
		for strc of-type character = (char str curr)
		do (if (char/= valc strc) (return nil))
		   (incf curr)
		finally (return t)))))))

(defpattern (unref) ((pat :pat) &optional (tag :tag))
  (with-gensyms ($result)
    `(with-save (tags)
       (let ((,$result ,(compile-expr opts pat)))
	 (when ,$result
	   ,(if tag
		`(tscope-tag! tags tags-bak ,tag)
		`(restore tags))
	   ,$result))))
  (let ((p (assemble-expr opts pat)))
    (lift-cond (scope!) ((tag (tscope-tag! tags tags-bak tag))
			 (t (restore tags)))
      (pat-lambda (tags)
	(with-save (tags)
	  (when-let ((result (funcall p state)))
	    (scope!)
	    result))))))

(defpattern (constant) ((thing :any) &optional (tag :tag))
  (with-gensyms ($thing)
    `(let ((,$thing (quote ,thing)))
       (push-item! ,$thing ,tag)
       t))
  (if tag
      (pat-lambda (caps tags accum accum?) (push-item! thing tag) t)
      (pat-lambda (caps accum accum?) (push-item! thing) t)))
      

(defpattern (position $) (&optional (tag :tag))
  `(progn (push-item! curr ,tag) t)
  (if tag
      (pat-lambda (curr caps tags accum accum?) (push-item! curr tag) t)
      (pat-lambda (curr caps accum accum?) (push-item! curr) t)))

(defun compile-linecol (line-or-col tag)
  (with-gensyms ($line $col)
    `(progn
       (unless line-map?
	 (build-linemap! line-map str)
	 (setf line-map? t))
       (multiple-value-bind (,$line ,$col) (search-line line-map curr)
	 (declare (ignorable ,$line ,$col))
	 (push-item! ,(if (eq line-or-col :line) $line $col) ,tag))
       t)))
(defun assemble-linecol (line-or-col tag)
  (lift-cond (lc) (((eq line-or-col :line) line)
		   (t col))
    (lift-cond (push!) ((tag (push-item! (lc) tag))
			(t (push-item! (lc))))
      (pat-lambda (str curr line-map line-map? caps tags accum accum?)
	(progn
	  (unless line-map?
	    (build-linemap! line-map str)
	    (setf line-map? t))
	  (multiple-value-bind (line col) (search-line line-map curr)
	    (declare (ignorable line col))
	    (push!))
	  t)))))

(defpattern (line) (&optional (tag :tag))
  (compile-linecol :line tag)
  (assemble-linecol :line tag))
(defpattern (column) (&optional (tag :tag))
  (compile-linecol :col tag)
  (assemble-linecol :col tag))

(add-type! :index (list (lambda (n) (and (integerp n)
					 (>= n 0)))
			"a non-negative integer"))
(defpattern (argument) ((n :index) &optional (tag :tag))
  `(when (< -1 ,n (length args))
     (push-item! (aref args ,n) ,tag)
     t)
  (lift-cond (push!) ((tag (push-item! (aref args n) tag))
		      (t (push-item! (aref args n))))
    (pat-lambda (caps tags accum accum? args)
      (when (< -1 n (length args))
	(push!)
	t))))

(defun peg-error? (name)
  (or (and (symbolp name)
	   (subtypep name 'condition))
      (stringp name)))

(add-type! :error (list #'peg-error? "error message or symbol denoting condition"))

(define-condition peg-error (error)
  ((pat :initarg :pat :reader error-pat)
   (matched :initarg :matched :reader error-matched)
   (caps :initarg :caps :reader error-caps))
  (:report (lambda (e s)
	     (let ((p (error-pat e))
		   (m (error-matched e)))
	       (when p
		 (when (/= (length m) 0)
		   (format s "~s is " m))
		 (format s "~s" p))))))

(defpattern (error) (&optional (pat :pat) (err :error))
  (with-gensyms ($matched? $capped)
    (if (and pat (subtypep (or err 'peg-error) 'peg-error))
	`(with-save (curr caps tags accum accum?)
	   (setf accum? nil)
	   (let ((,$matched? ,(compile-expr opts pat))
		 (,$capped (cdr caps-bak)))
	     (when ,$matched?
	       (error ',(or err 'peg-error)
		      :pat ',pat
		      :matched (subseq str curr-bak curr)
		      :caps ,$capped))
	     (restore curr caps tags accum accum?)
	     t))
	`(error ',(or err 'peg-error))))
  (if (and pat (subtypep (or err 'peg-error) 'peg-error))
      (let ((p (assemble-expr opts pat)))
	(pat-lambda (str curr caps tags accum accum?)
	  (with-save (curr caps tags accum accum?)
	    (setf accum? nil)
	    (let ((matched? (funcall p state))
		  (capped (cdr caps-bak)))
	      (when matched?
		(error (or err 'peg-error)
		       :pat pat
		       :matched (subseq str curr-bak curr)
		       :caps capped))
	      (restore curr caps tags accum accum?)
	      t))))
      (pat-lambda () (error (or err 'peg-error)))))

(defpattern (lenprefix) ((n-pat :pat) (r-pat :pat)) ;;Grouped in with capture because it manipulates the stack
  (with-gensyms ($matched $capped $count)
    `(with-save (accum? caps tags)
       (setf accum? nil)
       (let ((,$matched ,(compile-expr opts n-pat))
	     (,$capped (cdr caps-bak)))
	 (restore accum? caps tags)
	 (when (and ,$matched ,$capped)
	   (let ((,$count (first ,$capped)))
	     (when (positive-integer-p ,$count)
	       (loop repeat ,$count
		     for ,$matched = ,(compile-expr opts r-pat)
		     unless ,$matched do (return nil)
		     finally (return t))))))))
  (let ((n (assemble-expr opts n-pat))
	(r (assemble-expr opts r-pat)))
    (pat-lambda (curr caps accum? accum tags)
      (with-save (accum? caps tags)
	(setf accum? nil)
	(let ((matched (funcall n state))
	      (capped (cdr caps-bak)))
	  (restore accum? caps tags)
	  (when (and matched capped)
	    (let ((count (first capped)))
	      (when (positive-integer-p count)
		(loop repeat count
		      for matched = (funcall r state)
		      unless matched do (return nil)
		      finally (return t))))))))))

(add-type! :radix (list (lambda (n)
			  (or (null n)
			      (and (integerp n) (<= 2 n 36)))
			  "integer between 2 and 36")))

(defpattern (integer) ((pat :pat) &optional (radix :radix) (tag :tag))
  (with-gensyms ($region $reg-len $int $int-len)
    `(with-save (curr)
       (when ,(compile-expr opts pat)
	 (let ((,$region (subseq str curr-bak curr))
	       (,$reg-len (- curr curr-bak)))
	   (multiple-value-bind (,$int ,$int-len)
	       (parse-integer ,$region :radix ,(or radix 10) :junk-allowed t)
	     (when (and ,$int (= ,$int-len ,$reg-len))
	       (push-item! ,$int ,tag)
	       t))))))
  (let ((rad (or radix 10))
	(p (assemble-expr opts pat)))
    (lift-cond (push!) ((tag (push-item! int tag))
			(t (push-item! int)))
      (pat-lambda (curr str tags caps accum accum?)
	(with-save (curr)
	  (when (funcall p state)
	    (let ((region (subseq str curr-bak curr))
		  (reg-len (- curr curr-bak)))
	      (multiple-value-bind (int int-len)
		  (parse-integer region :radix rad :junk-allowed t)
		(when (and int (= int-len reg-len))
		  (push!)
		  t)))))))))
			
